areas:
  ottawa:
    country_code: ca
    country: Canada
    city: Ottawa
  zurich:
    country_code: ch
    country: Switzerland
    city: Zurich

search:
  main_key:
  prefix:
  suffix:
  custom_search:
    - Security Automation Engineer

parse:
  remote:
    is:
      - test1
      - test2
    not:
      - test3
      - test4
  us_only:
    is:
      - test5
      - test6
    not:
      - test7
      - test8
  