areas:
  ottawa:
    country_code: ca
    country: Canada
    city: Ottawa
  zurich:
    country_code: ch
    country: Switzerland
    city: Zurich

search:
  main_key:
    - Security
    - Network
  prefix:
    - Junior
  suffix:
    - Engineer
    - Administrator
  custom_search:
    - Security Automation Engineer

  